### PR TITLE
css-map.json remapped a lot of class

### PR DESCRIPTION
**Pull request by TheGeeKing**

### CODE REVIEW

**Review by afonsojramos — APPROVED** [review]
Looking good! A small step towards the remapping!

**Comment by TheGeeKing** [comment]
Yep will continue but I will need your help for something

**Comment by afonsojramos** [comment]
Merged manually to fix formatting.

**Comment by TheGeeKing** [comment]
> Merged manually to fix formatting.

Oh yep sorry will do it on the future remap commits

**Comment by JulienMaille** [comment]
How do you automate that remapping?

**Comment by TheGeeKing** [comment]
Was manual remapping. I took an element from Spicetify and the same from Spotify latest update and replace the class name in the json. I did 100+ class names. Yes it takes a lot of time.

**Pull request closed without merging**
