### PR TITLE
CSS map: update 'more albums by artist' shelf

### PR DESCRIPTION
**Pull request by GeorgeHahn**
From Spotify for Windows 1.1.76.447.g11f432d8

### CODE REVIEW

**Comment by afonsojramos** [comment]
@itsmeow this has happened before right? Where we had two different keys for the same value?

@GeorgeHahn can you send a screenshot of the html hierarchy where this class is present?

**Comment by GeorgeHahn** [comment]
@afonsojramos 
image

image

**Comment by itsmeow** [comment]
Two keys is fine - khanhas wanted the old ones around so it's probably unused.

**Review by itsmeow — APPROVED** [review]

**Comment by afonsojramos** [comment]
Thanks @itsmeow @GeorgeHahn!

**Pull request merged**
