### PR TITLE
Fade album art and background image in fullAppDisplay extension

### PR DESCRIPTION
**Pull request by julthon**
I added smooth fading for the fullAppDisplay extension since a song change flickered for a short period while loading the image. This is done by preloading the new image and updating the actual image source 0.5s later as well as adding a background transition.

### CODE REVIEW

**Comment by khanhas** [comment]
Thank you for your contribution.

The transition lags a lot when Spotify window is maximised or in full screen mode. Does it happen to you?

**Comment by julthon** [comment]
The transition is smooth on my workstation pc, but not so much on my low-end notebook. I think it's still way better than the sudden change without transition.
A possibility would be to include a context menu option to toggle the transition animation.

**Comment by khanhas** [comment]
Adding context menu option would be wise, thank you.

**Comment by khanhas** [comment]
Hi, I just made a few modification on UI update code. Now it's event based instead of waiting 500ms. Can you test it out on your end and see if the animation is still smooth:
https://raw.githubusercontent.com/khanhas/spicetify-cli/master/Extensions/fullAppDisplay.js

**Comment by julthon** [comment]
Hi, the event based trigger seems to work just as well! I added another css property which drastically reduces the lag during the animation. I will open another pull request.

**Pull request merged**
