### PR TITLE
Add shortcuts for nextSong previousSong increaseVolume decreaseVolume…

### PR DESCRIPTION
**Pull request by InteractiveNinja**
Code by @stankovictab Issue #1355

### CODE REVIEW

**Comment by khanhas** [comment]
Do these default keyboard shortcuts actually not work on all Linux distros or just yours? Can I get some more input?
Also wrap them in a if condition checking OS, I'm sure on Windows and MacOS they work just fine.

**Comment by stankovictab** [comment]
@khanhas That's right, they do work fine on Windows, \
however I know from experience and from my friends that the shortcut doesn't work on Ubuntu, Kubuntu, Linux Mint or Manjaro. \
It's been an active issue for a while now, you can see the issue [here on the Spotify Community forum](https://community.spotify.com/t5/Desktop-Linux/Forward-and-back-keyboard-shortcuts-no-longer-working/td-p/5257504). \
It appears to be the same [on Mac](https://community.spotify.com/t5/Desktop-Mac/Forward-and-back-keyboard-shortcut-feature-no-longer-working/m-p/5245215), but I haven't experimented with it.\
I'll add the OS check, it should work fine, but please correct it if it's wrong. 🙂

**Comment by stankovictab** [comment]
This should do the trick.
```js
function nextSong() {
	if (window.navigator.userAgent.indexOf("Win") == -1) // Works only on Linux and Mac
		document.querySelector(".main-skipForwardButton-button").click();
	}

function previousSong() {
	if (window.navigator.userAgent.indexOf("Win") == -1) // Works only on Linux and Mac
		document.querySelector(".main-skipBackButton-button").click();
	}

function increaseVolume() {
	if (window.navigator.userAgent.indexOf("Win") == -1) // Works only on Linux and Mac
		Spicetify.Player.origin.setVolume(Spicetify.Player.getVolume() + 0.1);
	}

function decreaseVolume() {
	if (window.navigator.userAgent.indexOf("Win") == -1) // Works only on Linux and Mac
		Spicetify.Player.origin.setVolume(Spicetify.Player.getVolume() - 0.1);
	}
```

**Comment by khanhas** [comment]
Okay then.
But please wrap functions and `Spicetify.KeyboardShortcut` calls in one if condition, not each of these like stankovictab's code.
We don't need to add these shortcuts handler for Windows since they work out of the box.

**Comment by InteractiveNinja** [comment]
Do we really need to also check the function definitions?

**Pull request merged**
