### PR TITLE
Update community badge

### PR DESCRIPTION
**Pull request by morpheusthewhite**

### CODE REVIEW

**Comment by itsmeow** [comment]
Might I suggest we add the Discord to the README as well?

**Comment by morpheusthewhite** [comment]
Do we want to? Isn't it better to group the community around a single place instead of spreading them across different platforms?

**Comment by CharlieS1103** [comment]
@morpheusthewhite As far as I can tel the discord is much more active than the reddit, and I find it to be a much easier platform to use when helping people with spicetify or working with people to help fix spicetify. Especially with the new threading function.

**Comment by TheGeeKing** [comment]
Yep, totally agree with Charlie.

Discord is the best place to discuss and help about Spicetify, you should check it a lot of people are active on it. It surprises me that the discord wasn't easily accessible to everyone on the github. We should definitely add it to the front page.

**Comment by morpheusthewhite** [comment]
Ok then, I'll add it.

Thanks for the feedback btw.

**Comment by TheGeeKing** [comment]
You're welcome. https://discord.gg/VnevqPp2Rr

**Comment by morpheusthewhite** [comment]
I asked the discord admin to enable the badge on the server, it will soon be shown properly

**Review by afonsojramos — APPROVED** [review]

**Pull request merged**
