### PR TITLE
Update css-map.json

### PR DESCRIPTION
**Pull request by TheGeeKing**
- remapped `collection-collectionEntityHeroCard-*` css

Fixes https://github.com/JulienMaille/dribbblish-dynamic-theme/issues/117

### CODE REVIEW

**Comment by TheGeeKing** [comment]
@khanhas so for compatibility I should add them and not replace them right? If so, I will correct my PR.

**Comment by khanhas** [comment]
> @khanhas so for compatibility I should add them and not replace them right? If so, I will correct my PR.

If you don't mind, yes please

**Comment by TheGeeKing** [comment]
> If you don't mind, yes please

Done 😃

**Comment by JulienMaille** [comment]
@TheGeeKing One is missing for our theme to work :'(
`collection-collectionEntityHeroCard-likedSongs` is now either `GbXSJaVC61cQYqOVDfz9` or `aMCCvuHnzEolcWDV6Dep`

**Comment by TheGeeKing** [comment]
> @TheGeeKing One is missing for our theme to work :'(
> `collection-collectionEntityHeroCard-likedSongs` is now either `GbXSJaVC61cQYqOVDfz9` or `aMCCvuHnzEolcWDV6Dep`

Oh OK will check that later today 🙂

**Pull request merged**
