### PR TITLE
Changed Custom app React symbols regex to match change in spotify client

### LINKED ISSUE #845: Cannot find symbol for Custom app React symbols
## ℹ Computer information

- Spotify version: 1.1.63.566.g62675f37-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

I'm trying to apply [this theme](https://github.com/daksh777/spotifynopremium) but I get the "Cannot find symbol for Custom app React symbols" error and Spotify becomes blank after applying it.
Tried removing extensions too but it doesn't help.

### ✔️ Expected result

The theme should be applied normally

### ❌ Actual result

I get a blank screen

### PR DESCRIPTION
**Pull request by adriankarlen**
Fixes #845

### CODE REVIEW

**Comment by nils-kt** [comment]
My Spotify is still blank after the patch.

Screen

1. Re-Installed Spotify
2. Applied patch

```info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
Transferring custom apps:
OK
success Spotify is spiced up!
```

**Comment by ElReyCoraje** [comment]
> Fixes #845

Bro , did u fix it ?
Because i can't Lol

**Comment by ElReyCoraje** [comment]
> My Spotify is still blank after the patch.
> 
> Screen
> 
> 1. Re-Installed Spotify
> 2. Applied patch
> 
> ```
> info Clear current backup:
> success Backup is cleared.
> Backing up app files:
> OK
> Extracting:
> OK
> Preprocessing:
> OK
> OK
> success Everything is ready, you can start applying now!
> Copying raw assets:
> OK
> Transferring user.css:
> OK
> Applying additional modifications:
> OK
> Transferring custom apps:
> OK
> success Spotify is spiced up!
> ```
> 
> Because:
> 
> ```
> xpui.js:1 Uncaught TypeError: Cannot read property 'lazy' of undefined
>     at Object.94973 (xpui.js:1)
>     at c (xpui.js:1)
>     at xpui.js:1
>     at Function.c.O (xpui.js:1)
>     at xpui.js:1
>     at xpui.js:1
> `

Bro did you fix it ?

**Comment by CharlieS1103** [comment]
For all those wondering, the patch hasn't actually been released yet, this branch needs to be merged with the main one, and then you can go about your spicetify business lol.

**Comment by nils-kt** [comment]
> For all those wondering, the patch hasn't actually been released yet, this branch needs to be merged with the main one, and then you can go about your spicetify business lol.

This patch does not work either. We have to wait for khanas.

**Comment by afonsojramos** [comment]
Unfortunately, this does not seem to solve the issue.

**Pull request closed without merging**
