### PR TITLE
Update fullAppDisplay.js

### PR DESCRIPTION
**Pull request by McStecca**
Changed the annoying minimize button to access fullscreen to the maximize one

### CODE REVIEW

**Comment by JulienMaille** [comment]
Have a look here :)
https://github.com/khanhas/spicetify-cli/pull/260#issuecomment-678099470

**Comment by McStecca** [comment]
It doesn't make sense, i understand that fullAppDisplay.js and fullscreen are two different things with different functions, but the minimize button is unaesthetic. I could search for a different icon if it's necessary

**Comment by JulienMaille** [comment]
I agree the minimise icon is misleading, you can have a look at availables icons here: https://github.com/morpheusthewhite/spicetify-themes/pull/272#issuecomment-779090321
maybe the "tv" icon?
image

**Comment by khanhas** [comment]
If it's unaesthetic to you, just change it locally whatever you prefer ;)

**Pull request closed without merging**
