### PR TITLE
Fix Lyrics Plus Karaoke position error

### LINKED ISSUE #1099: The lyrics-plus custom app isn't working as intended (stuck at the initial state)
## ℹ Computer information

- Spotify version: 1.1.68.632-1
- Spicetify version: 2.6.6

## 📝 Provide detailed reproduction steps (if any)

1. Download Spicetify and enable the custom app lyrics-plus
2. Play a song synced on Musixmatch
3. Play a moment when a line is being singed

### ✔️ Expected result

_What is the expected result of the above steps?_

The vocal line should be focused and the visuals have to update.

### ❌ Actual result

_What is the actual result of the above steps?_

Nothing happens.

## 📷 Screenshots

_Are there any useful screenshots?_

You can see in the following screenshot that I'm playing a song and I'm at the near-end of the track, where lyrics has almost ended, however, lyrics-plus still shows the start of the lyrics, nothing has moved from the initial state.

## 🔎 Research trail

You might notice, in the previous screenshot, that I have my element inspector opened, and the console consistently spits "Cannot read property 'position_as_of_timestamp' of undefined" errors happening on [this line](https://github.com/khanhas/spicetify-cli/blob/master/CustomApps/lyrics-plus/Pages.js#L102). That would mean that PlayerState's value of [position_as_of_timestamp](https://github.com/khanhas/spicetify-cli/blob/master/globals.d.ts#L42) is never written, and, lyrics-plus using this value to update, would ultimately crash too.

When fidgeting with the Console tab, I noticed `Spicetify.Player.origin2.state.playback` returned `undefined`. The problem probably comes from the fact that this value does not exist. As I'm fairly inexperienced with Typescript, I don't really know where to look for to repair such issue. I'm not sure if that's caused by a Spotify update, for instance if they changed the name of their variables (if the value of `state` or `playback` is provided by Spotify themselves) or if the issue comes from spicetify not initializing `playback` correctly for some reason. I tried checking for files containing of `playback` in spicetify but I couldn't find anything interesting.

### PR DESCRIPTION
**Pull request by itsmeow**
Fixes #1099

### CODE REVIEW

**Comment by Ballasi** [comment]
Works for me!

**Comment by afonsojramos** [comment]
I'm not sure if this is fixing anything as everything detailed in #1090 is still happening.

@itsmeow do you have a MusicXMatch token?

**Comment by afonsojramos** [comment]
Sometimes I wonder if it is just lack of lyrics availability from MusicXMatch 🤔

**Comment by itsmeow** [comment]
This PR does not attempt to address #1090, this only addresses the error in #1099. The two errors are completely unrelated and in different apps.

**Pull request merged**
